### PR TITLE
feat: 事件中心查询优化，时间范围超过1天的查询， 按天分片并发 --story=117511769

### PR DESCRIPTION
**Pull request by TangMoonX**
# Reviewed, transaction id: 8599

### CODE REVIEW

**Comment by TangMoonX** [comment]
AlertDateHistogramResource接口自测截图
一、不分片时
1、查询6天的
image
2、查询30天的
image
3、查询200天的，跨2个年份
image

二、分片时
1、查询6天的
image
跟不分片时的数据对比一致
image
2、查询30天的
image
跟不分片时的数据对比一致
image
3、查询200天的，跨2个年份的
image
跟不分片时的数据对比一致
image


三、参数
1、6天的
param = {
    "bk_biz_ids": [
        3
    ],
    "conditions": [],
    "query_string": "",
    "status": [],
    "start_time": 1717224497,
    "end_time": 1717742897,
    "interval": "auto",
    "bk_biz_id": 2
}
2、30天的
param = {
    "bk_biz_ids": [
        3
    ],
    "conditions": [],
    "query_string": "",
    "status": [],
    "start_time": 1715150603,
    "end_time": 1717742603,
    "interval": "auto",
    "bk_biz_id": 2
}
3、200天的
param = {
    "bk_biz_ids": [
        3
    ],
    "conditions": [],
    "query_string": "",
    "status": [],
    "start_time": 1700981465,
    "end_time": 1718261465,
    "interval": "auto",
    "bk_biz_id": 2
}

**Comment by TangMoonX** [comment]
AlertTopNResource接口自测截图
一、不分片
1、6天的
image

2、30天的
image

二、分片时
1、6天的
image
跟不分片时的数据对比一致
image

2、30天的
image
跟不分片时的数据对比一致
image

三、参数
1、6天的
param = {
    "bk_biz_ids": [
        3
    ],
    "status": [],
    "conditions": [],
    "query_string": "",
    "start_time": 1717554259,
    "end_time": 1718072659,
    "fields": [
        "alert_name",
        "metric",
        "duration",
        "ip",
        "bk_cloud_id",
        "strategy_id",
        "strategy_name",
        "assignee",
        "bk_service_instance_id",
        "appointee",
        "labels",
        "plugin_id",
        "ipv6"
    ],
    "size": 10,
    "bk_biz_id": 2
}
2、30天的
param = {
    "bk_biz_ids": [
        3
    ],
    "status": [],
    "conditions": [],
    "query_string": "",
    "start_time": 1715157510,
    "end_time": 1717749510,
    "fields": [
        "alert_name",
        "metric",
        "duration",
        "ip",
        "bk_cloud_id",
        "strategy_id",
        "strategy_name",
        "assignee",
        "bk_service_instance_id",
        "appointee",
        "labels",
        "plugin_id",
        "ipv6"
    ],
    "size": 10,
    "bk_biz_id": 2
}

**Comment by TangMoonX** [comment]
SearchActionResource接口自测截图
一、不分片
1、6天的
image

2、30天的
image

二、分片时
1、6天的，与上面不分片时的数据一致
image

2、30天的，与上面不分片时的数据一致
image

三、参数
1、6天的
param = {
    "bk_biz_ids": [
        3
    ],
    "status": [],
    "conditions": [],
    "query_string": "",
    "start_time": 1717222396,
    "end_time": 1717740796,
    "ordering": [],
    "page": 1,
    "page_size": 0,
    "show_overview": True,
    "show_aggs": False,
    "record_history": False,
    "alert_ids": [],
    "bk_biz_id": 2
}

2、30天的
param = {
    "bk_biz_ids": [
        3
    ],
    "status": [],
    "conditions": [],
    "query_string": "",
    "start_time": 1715148950,
    "end_time": 1717740950,
    "ordering": [],
    "page": 1,
    "page_size": 0,
    "show_overview": True,
    "show_aggs": False,
    "record_history": False,
    "alert_ids": [],
    "bk_biz_id": 2
}

**Comment by TangMoonX** [comment]
ListAlertTagsResource 接口自测截图
一、不分片时
1、100天
image
二、分片时
1、100天，与上述不分片时结果一致
image

三、参数
1、100天
param = {
    "bk_biz_ids": [
        3
    ],
    "status": [],
    "conditions": [],
    "query_string": "",
    "start_time": 1709609738,
    "end_time": 1718249738,
    "bk_biz_id": 2
}

**Review by chenguo367 — APPROVED** [review]

**Pull request merged**
